from enum import Enum


class BoxType(Enum):
    UNKNOWN = "UNKNOWN"
    FLOWING_TEXT = "FLOWING_TEXT"
    HEADING_TEXT = "HEADING_TEXT"
    PULLOUT_TEXT = "PULLOUT_TEXT"
    VERTICAL_TEXT = "VERTICAL_TEXT"
    CAPTION_TEXT = "CAPTION_TEXT"
    EQUATION = "EQUATION"
    INLINE_EQUATION = "INLINE_EQUATION"
    TABLE = "TABLE"
    FLOWING_IMAGE = "FLOWING_IMAGE"
    HEADING_IMAGE = "HEADING_IMAGE"
    PULLOUT_IMAGE = "PULLOUT_IMAGE"
    HORZ_LINE = "HORZ_LINE"
    VERT_LINE = "VERT_LINE"
    NOISE = "NOISE"
    COUNT = "COUNT"
